# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [58]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
# from api_keys import g_key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [59]:

cities_df = pd.read_csv('../WeatherPy/output_data/cities.csv')
cities_df.dropna(inplace = True)
cities_df.head()

,city_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,saint-augustin,100,CA,1597861191,92,51.23,-58.65,58.59,6.89
1,1,severo-kurilsk,100,RU,1597861209,91,50.68,156.12,51.49,14.09
2,2,belyy yar,25,RU,1597861610,93,53.60,91.39,53.60,2.24
3,3,ribeira grande,40,PT,1597861612,53,38.52,-28.70,75.20,10.29
4,4,shenjiamen,0,CN,1597861613,89,29.96,122.30,80.58,12.03

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [60]:
# Store latitude and longitude in locations
locations = cities_df[["Lat", "Lng"]]

# Fill NaN values and convert to float
rating = cities_df["Humidity"].astype(float)

In [61]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=rating, 
                                 dissipating=False, 
                                 max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [62]:
weather_cond = cities_df.loc[pd.to_numeric(cities_df["Max Temp"]).astype(float).between(71, 79, inclusive=False)]
weather_cond_wind = weather_cond.loc[pd.to_numeric(cities_df["Wind Speed"]).astype(float) <10]
# weather_cond_wind
weather_cond_wind_cloud = weather_cond_wind.loc[pd.to_numeric(cities_df["Cloudiness"]).astype(float) <40]
weather_cond_wind_cloud

,city_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
9,9,albany,32,US,1597860983,49,42.60,-73.97,73.99,7.78
27,27,lasem,19,ID,1597861631,75,-6.69,111.45,77.50,6.11
61,61,kieta,38,PG,1597861231,76,-6.22,155.63,78.17,3.69
78,78,bethel,20,US,1597861213,77,41.37,-73.41,72.00,5.82
89,89,tautira,20,PF,1597861682,69,-17.73,-149.15,78.80,2.24
157,157,cap malheureux,26,MU,1597861733,65,-19.98,57.61,72.00,3.00
185,185,tura,15,IN,1597861259,89,25.52,90.22,75.06,7.45
212,212,cayenne,30,GF,1597861194,94,4.93,-52.33,78.80,4.70
237,237,mingaora,0,PK,1597861722,66,34.78,72.36,76.06,4.79
242,242,honiara,20,SB,1597861776,100,-9.43,159.95,73.40,2.24
255,255,takoradi,0,GH,1597861816,85,4.88,-1.76,75.69,9.71
256,256,yutsa,0,RU,1597861817,35,43.96,43.01,73.00,4.47
271,271,naze,0,JP,1597861830,94,28.37,129.48,78.80,2.24
297,297,hakodate,16,JP,1597861854,91,41.78,140.74,72.48,5.77
316,316,loa janan,0,ID,1597861871,96,-0.58,117.09,72.61,2.28
317,317,waingapu,0,ID,1597861683,78,-9.66,120.26,72.14,4.18
379,379,bontang,12,ID,1597861922,86,0.13,117.50,75.99,6.02
403,403,grand gaube,3,MU,1597861942,65,-20.01,57.66,72.00,4.00
408,408,tendo,0,JP,1597861945,81,38.35,140.37,73.99,1.90
418,418,tiznit,0,MA,1597861952,62,29.58,-9.50,72.77,3.78
421,421,ishinomaki,0,JP,1597861956,90,38.42,141.30,73.31,3.87
456,456,poum,0,NC,1597861807,70,-20.23,164.02,71.94,8.88
457,457,aksaray,0,TR,1597861986,23,38.37,34.03,77.00,1.12
461,461,hasaki,20,JP,1597861774,100,35.73,140.83,75.20,3.36
492,492,tawau,20,MY,1597862017,94,4.25,117.89,77.00,1.12
504,504,phangnga,20,TH,1597862025,88,8.45,98.53,78.80,3.36
505,505,athabasca,0,CA,1597861862,40,54.72,-113.29,72.79,5.64
511,511,goderich,0,CA,1597861852,69,43.75,-81.72,72.00,3.00
515,515,pokrovsk,21,UA,1597862033,47,48.28,37.18,72.93,9.15
516,516,michigan city,1,US,1597861810,64,41.71,-86.89,75.00,9.17
534,534,samarai,0,PG,1597862048,70,-10.62,150.67,74.68,3.76
536,536,varna,20,BG,1597862049,64,43.22,27.92,75.20,5.82
538,538,baraboo,1,US,1597862050,44,43.47,-89.74,78.80,8.05
543,543,bambanglipuro,2,ID,1597862057,87,-7.95,110.28,72.72,4.61
546,546,luangwa,0,ZM,1597862059,30,-15.62,30.42,75.42,2.80
562,562,brigantine,1,US,1597862072,69,39.41,-74.36,75.99,3.36

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [63]:
# store into hotel_df
hotel_df = weather_cond_wind_cloud
hotel_df

,city_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
9,9,albany,32,US,1597860983,49,42.60,-73.97,73.99,7.78
27,27,lasem,19,ID,1597861631,75,-6.69,111.45,77.50,6.11
61,61,kieta,38,PG,1597861231,76,-6.22,155.63,78.17,3.69
78,78,bethel,20,US,1597861213,77,41.37,-73.41,72.00,5.82
89,89,tautira,20,PF,1597861682,69,-17.73,-149.15,78.80,2.24
157,157,cap malheureux,26,MU,1597861733,65,-19.98,57.61,72.00,3.00
185,185,tura,15,IN,1597861259,89,25.52,90.22,75.06,7.45
212,212,cayenne,30,GF,1597861194,94,4.93,-52.33,78.80,4.70
237,237,mingaora,0,PK,1597861722,66,34.78,72.36,76.06,4.79
242,242,honiara,20,SB,1597861776,100,-9.43,159.95,73.40,2.24
255,255,takoradi,0,GH,1597861816,85,4.88,-1.76,75.69,9.71
256,256,yutsa,0,RU,1597861817,35,43.96,43.01,73.00,4.47
271,271,naze,0,JP,1597861830,94,28.37,129.48,78.80,2.24
297,297,hakodate,16,JP,1597861854,91,41.78,140.74,72.48,5.77
316,316,loa janan,0,ID,1597861871,96,-0.58,117.09,72.61,2.28
317,317,waingapu,0,ID,1597861683,78,-9.66,120.26,72.14,4.18
379,379,bontang,12,ID,1597861922,86,0.13,117.50,75.99,6.02
403,403,grand gaube,3,MU,1597861942,65,-20.01,57.66,72.00,4.00
408,408,tendo,0,JP,1597861945,81,38.35,140.37,73.99,1.90
418,418,tiznit,0,MA,1597861952,62,29.58,-9.50,72.77,3.78
421,421,ishinomaki,0,JP,1597861956,90,38.42,141.30,73.31,3.87
456,456,poum,0,NC,1597861807,70,-20.23,164.02,71.94,8.88
457,457,aksaray,0,TR,1597861986,23,38.37,34.03,77.00,1.12
461,461,hasaki,20,JP,1597861774,100,35.73,140.83,75.20,3.36
492,492,tawau,20,MY,1597862017,94,4.25,117.89,77.00,1.12
504,504,phangnga,20,TH,1597862025,88,8.45,98.53,78.80,3.36
505,505,athabasca,0,CA,1597861862,40,54.72,-113.29,72.79,5.64
511,511,goderich,0,CA,1597861852,69,43.75,-81.72,72.00,3.00
515,515,pokrovsk,21,UA,1597862033,47,48.28,37.18,72.93,9.15
516,516,michigan city,1,US,1597861810,64,41.71,-86.89,75.00,9.17
534,534,samarai,0,PG,1597862048,70,-10.62,150.67,74.68,3.76
536,536,varna,20,BG,1597862049,64,43.22,27.92,75.20,5.82
538,538,baraboo,1,US,1597862050,44,43.47,-89.74,78.80,8.05
543,543,bambanglipuro,2,ID,1597862057,87,-7.95,110.28,72.72,4.61
546,546,luangwa,0,ZM,1597862059,30,-15.62,30.42,75.42,2.80
562,562,brigantine,1,US,1597862072,69,39.41,-74.36,75.99,3.36

In [64]:
hotel_df["Hotel Name"] = ""
hotel_df

<ipython-input-64-56b4fe6e59b6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

,city_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
9,9,albany,32,US,1597860983,49,42.60,-73.97,73.99,7.78,
27,27,lasem,19,ID,1597861631,75,-6.69,111.45,77.50,6.11,
61,61,kieta,38,PG,1597861231,76,-6.22,155.63,78.17,3.69,
78,78,bethel,20,US,1597861213,77,41.37,-73.41,72.00,5.82,
89,89,tautira,20,PF,1597861682,69,-17.73,-149.15,78.80,2.24,
157,157,cap malheureux,26,MU,1597861733,65,-19.98,57.61,72.00,3.00,
185,185,tura,15,IN,1597861259,89,25.52,90.22,75.06,7.45,
212,212,cayenne,30,GF,1597861194,94,4.93,-52.33,78.80,4.70,
237,237,mingaora,0,PK,1597861722,66,34.78,72.36,76.06,4.79,
242,242,honiara,20,SB,1597861776,100,-9.43,159.95,73.40,2.24,
255,255,takoradi,0,GH,1597861816,85,4.88,-1.76,75.69,9.71,
256,256,yutsa,0,RU,1597861817,35,43.96,43.01,73.00,4.47,
271,271,naze,0,JP,1597861830,94,28.37,129.48,78.80,2.24,
297,297,hakodate,16,JP,1597861854,91,41.78,140.74,72.48,5.77,
316,316,loa janan,0,ID,1597861871,96,-0.58,117.09,72.61,2.28,
317,317,waingapu,0,ID,1597861683,78,-9.66,120.26,72.14,4.18,
379,379,bontang,12,ID,1597861922,86,0.13,117.50,75.99,6.02,
403,403,grand gaube,3,MU,1597861942,65,-20.01,57.66,72.00,4.00,
408,408,tendo,0,JP,1597861945,81,38.35,140.37,73.99,1.90,
418,418,tiznit,0,MA,1597861952,62,29.58,-9.50,72.77,3.78,
421,421,ishinomaki,0,JP,1597861956,90,38.42,141.30,73.31,3.87,
456,456,poum,0,NC,1597861807,70,-20.23,164.02,71.94,8.88,
457,457,aksaray,0,TR,1597861986,23,38.37,34.03,77.00,1.12,
461,461,hasaki,20,JP,1597861774,100,35.73,140.83,75.20,3.36,
492,492,tawau,20,MY,1597862017,94,4.25,117.89,77.00,1.12,
504,504,phangnga,20,TH,1597862025,88,8.45,98.53,78.80,3.36,
505,505,athabasca,0,CA,1597861862,40,54.72,-113.29,72.79,5.64,
511,511,goderich,0,CA,1597861852,69,43.75,-81.72,72.00,3.00,
515,515,pokrovsk,21,UA,1597862033,47,48.28,37.18,72.93,9.15,
516,516,michigan city,1,US,1597861810,64,41.71,-86.89,75.00,9.17,
534,534,samarai,0,PG,1597862048,70,-10.62,150.67,74.68,3.76,
536,536,varna,20,BG,1597862049,64,43.22,27.92,75.20,5.82,
538,538,baraboo,1,US,1597862050,44,43.47,-89.74,78.80,8.05,
543,543,bambanglipuro,2,ID,1597862057,87,-7.95,110.28,72.72,4.61,
546,546,luangwa,0,ZM,1597862059,30,-15.62,30.42,75.42,2.80,
562,562,brigantine,1,US,1597862072,69,39.41,-74.36,75.99,3.36,

In [65]:
hotel_df = hotel_df[["City",
                     "Lat",
                     "Lng",
                     "Humidity",
                     "Hotel Name"]]
hotel_df

               City    Lat     Lng  Humidity Hotel Name
9            albany  42.60  -73.97        49
27            lasem  -6.69  111.45        75
61            kieta  -6.22  155.63        76
78           bethel  41.37  -73.41        77
89          tautira -17.73 -149.15        69
157  cap malheureux -19.98   57.61        65
185            tura  25.52   90.22        89
212         cayenne   4.93  -52.33        94
237        mingaora  34.78   72.36        66
242         honiara  -9.43  159.95       100
255        takoradi   4.88   -1.76        85
256           yutsa  43.96   43.01        35
271            naze  28.37  129.48        94
297        hakodate  41.78  140.74        91
316       loa janan  -0.58  117.09        96
317        waingapu  -9.66  120.26        78
379         bontang   0.13  117.50        86
403     grand gaube -20.01   57.66        65
408           tendo  38.35  140.37        81
418          tiznit  29.58   -9.50        62
421      ishinomaki  38.42  141.30        90
456            poum -20.23  164.02        70
457         aksaray  38.37   34.03        23
461          hasaki  35.73  140.83       100
492           tawau   4.25  117.89        94
504        phangnga   8.45   98.53        88
505       athabasca  54.72 -113.29        40
511        goderich  43.75  -81.72        69
515        pokrovsk  48.28   37.18        47
516   michigan city  41.71  -86.89        64
534         samarai -10.62  150.67        70
536           varna  43.22   27.92        64
538         baraboo  43.47  -89.74        44
543   bambanglipuro  -7.95  110.28        87
546         luangwa -15.62   30.42        30
562      brigantine  39.41  -74.36        69

In [70]:
#I spent a very long time trying to get this to work and just couldnt. 
#I watched lots of class videos and looked up activities and documentation. 
 
# find the closest restaurant of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "type": "hotel",
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]

    # get city name from df
    city_name = row['City']

#     # add keyword to params dict
    params['location'] = f"{lat},{lng}"

    # assemble url and make API request
    print(f"Retrieveing {index}: {city_name}")
    response = requests.get(base_url, 
                            params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"looking for hotels near{city_name}is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieveing 9: albany
Missing field/result... skipping.
------------
Retrieveing 27: lasem
Missing field/result... skipping.
------------
Retrieveing 61: kieta
Missing field/result... skipping.
------------
Retrieveing 78: bethel
Missing field/result... skipping.
------------
Retrieveing 89: tautira
Missing field/result... skipping.
------------
Retrieveing 157: cap malheureux
Missing field/result... skipping.
------------
Retrieveing 185: tura
Missing field/result... skipping.
------------
Retrieveing 212: cayenne
Missing field/result... skipping.
------------
Retrieveing 237: mingaora
Missing field/result... skipping.
------------
Retrieveing 242: honiara
Missing field/result... skipping.
------------
Retrieveing 255: takoradi
Missing field/result... skipping.
------------
Retrieveing 256: yutsa
Missing field/result... skipping.
------------
Retrieveing 271: naze
Missing field/result... skipping.
------------
Retrieveing 297: hakodate
Missing field/result... skipping.
------------
Retrieveing 316: loa janan
Missing field/result... skipping.
------------
Retrieveing 317: waingapu
Missing field/result... skipping.
------------
Retrieveing 379: bontang
Missing field/result... skipping.
------------
Retrieveing 403: grand gaube
Missing field/result... skipping.
------------
Retrieveing 408: tendo
Missing field/result... skipping.
------------
Retrieveing 418: tiznit
Missing field/result... skipping.
------------
Retrieveing 421: ishinomaki
Missing field/result... skipping.
------------
Retrieveing 456: poum
Missing field/result... skipping.
------------
Retrieveing 457: aksaray
Missing field/result... skipping.
------------
Retrieveing 461: hasaki
Missing field/result... skipping.
------------
Retrieveing 492: tawau
Missing field/result... skipping.
------------
Retrieveing 504: phangnga
Missing field/result... skipping.
------------
Retrieveing 505: athabasca
Missing field/result... skipping.
------------
Retrieveing 511: goderich
Missing field/result... skipping.
------------
Retrieveing 515: pokrovsk
Missing field/result... skipping.
------------
Retrieveing 516: michigan city
Missing field/result... skipping.
------------
Retrieveing 534: samarai
Missing field/result... skipping.
------------
Retrieveing 536: varna
Missing field/result... skipping.
------------
Retrieveing 538: baraboo
Missing field/result... skipping.
------------
Retrieveing 543: bambanglipuro
Missing field/result... skipping.
------------
Retrieveing 546: luangwa
Missing field/result... skipping.
------------
Retrieveing 562: brigantine
Missing field/result... skipping.
------------

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map

# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)
# Add the layer to the map
fig.add_layer(markers)
fig
# Display Map